services:
  messenger-viewer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - ARCHIVE_PATH=/app/archive
    restart: unless-stopped
    volumes:
      # Mount the server archive folder into the container.
      - /home/admh3/ffs/messages:/app/archive
    healthcheck:
      test: [ 'CMD', 'wget', '--quiet', '--tries=1', '--spider', 'http://localhost:3000' ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s
